apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    field.cattle.io/creatorId: user-mmwdw
    field.cattle.io/publicEndpoints: '[{"nodeName":"local:machine-vjd5p","addresses":["172.17.0.3"],"port":8501,"protocol":"TCP","podName":"default:exploration-data-container-776ccb47ff-44rx8","allNodes":false}]'
  creationTimestamp: "2021-01-26T04:21:40Z"
  generation: 27
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-exploration-data-container
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"exploration-data-container"}:
                f:image: {}
            f:terminationGracePeriodSeconds: {}
    manager: okteto
    operation: Update
    time: "2021-01-26T07:17:47Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
          f:workload.user.cattle.io/workloadselector: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:workload.user.cattle.io/workloadselector: {}
        f:strategy:
          f:type: {}
        f:template:
          f:metadata:
            f:annotations:
              .: {}
              f:cattle.io/timestamp: {}
              f:field.cattle.io/ports: {}
              f:field.cattle.io/publicEndpoints: {}
            f:labels:
              .: {}
              f:workload.user.cattle.io/workloadselector: {}
          f:spec:
            f:containers:
              k:{"name":"exploration-data-container"}:
                .: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8501,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:hostPort: {}
                    f:name: {}
                    f:protocol: {}
                f:resources: {}
                f:securityContext:
                  .: {}
                  f:allowPrivilegeEscalation: {}
                  f:privileged: {}
                  f:readOnlyRootFilesystem: {}
                  f:runAsNonRoot: {}
                f:stdin: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:tty: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/home/sidefxs/Documents/rancher_exp_app/"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:volumes:
              .: {}
              k:{"name":"explorationapp"}:
                .: {}
                f:hostPath:
                  .: {}
                  f:path: {}
                  f:type: {}
                f:name: {}
    manager: Go-http-client
    operation: Update
    time: "2021-01-31T16:11:26Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          k:{"type":"Available"}:
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
          k:{"type":"Progressing"}:
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: k3s
    operation: Update
    time: "2021-01-31T16:12:14Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:field.cattle.io/publicEndpoints: {}
    manager: rancher
    operation: Update
    time: "2021-01-31T16:12:14Z"
  name: exploration-data-container
  namespace: default
  resourceVersion: "7041366"
  selfLink: /apis/apps/v1/namespaces/default/deployments/exploration-data-container
  uid: ff72aeaf-f7e9-4c08-be33-8e6eb694da82
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-exploration-data-container
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-01-31T16:11:26Z"
        field.cattle.io/ports: '[[{"containerPort":8501,"dnsName":"exploration-data-container-hostport","hostPort":8501,"kind":"HostPort","name":"8501tcp85010","protocol":"TCP","sourcePort":8501}]]'
        field.cattle.io/publicEndpoints: '[{"addresses":["172.17.0.3"],"nodeId":"local:machine-vjd5p","port":8501,"protocol":"TCP"}]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-exploration-data-container
    spec:
      containers:
      - image: jayaro/exploration_data_app:latest
        imagePullPolicy: Always
        name: exploration-data-container
        ports:
        - containerPort: 8501
          hostPort: 8501
          name: 8501tcp85010
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /home/sidefxs/Documents/rancher_exp_app/
          name: explorationapp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /ExplorationDataApp
          type: ""
        name: explorationapp
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-01-31T16:12:14Z"
    lastUpdateTime: "2021-01-31T16:12:14Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-26T04:21:40Z"
    lastUpdateTime: "2021-01-31T16:12:14Z"
    message: ReplicaSet "exploration-data-container-776ccb47ff" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 27
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
